# Generated by Django 5.0.7 on 2024-10-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio_files')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='app.description')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='app.place')),
            ],
        ),
    ]
