# Generated by Django 5.0.7 on 2024-10-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
