# Generated by Django 5.0.7 on 2024-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_favoritehotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='Not located', max_length=100),
        ),
    ]
