# Generated by Django 5.0.7 on 2024-11-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_files'),
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
