# Generated by Django 5.0.7 on 2024-11-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_description_audio_delete_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='suggestion',
        ),
    ]
