# Generated by Django 5.0.7 on 2024-11-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_category_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='suggestion',
            field=models.TextField(default='suggestions.'),
        ),
    ]
