# Generated by Django 5.0.7 on 2024-11-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='suggestion',
        ),
    ]
