# Generated by Django 5.0.7 on 2025-02-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_place_popularity_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='popularity',
            new_name='visits',
        ),
    ]
