# Generated by Django 5.0.7 on 2025-02-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_popularity_place_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='free_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_plan',
            field=models.BooleanField(default=False),
        ),
    ]
