# Generated by Django 5.0.7 on 2025-02-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_customuser_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='without_plan',
            new_name='without_adds',
        ),
    ]
