# Generated by Django 5.0.7 on 2025-02-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_without_plan_customuser_without_adds'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
