# Generated by Django 5.0.7 on 2025-02-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customuser_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='without_adds',
            new_name='without_ads',
        ),
    ]
