# Generated by Django 5.0.7 on 2025-02-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_without_adds_customuser_without_ads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='without_ads',
            new_name='all_stars_plan',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='free_plan',
            new_name='starter_plan',
        ),
    ]
